# -*- coding: utf-8 -*-
"""CS5103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153zLPwLEfbFyteCfVkyrhv2yOt-q_kuY
"""

import decimal

def BigNumberComputation(a,op, b):
  if "+" in op:
    result=a+b
    decResult=decimal.Decimal(result)
    print("A+B= " + format(decResult, '.1e'))
    strResult=stringNumber(decResult)
    print(strResult)
    return decResult
  elif (op=="-"):
    result=b-a
    decResult=decimal.Decimal(result)
    print("A+B= " + format(decResult, '.1e'))
    strResult=stringNumber(decResult)
    print(strResult)
    return decResult  
  else:
    result=0
    print("Operand Not Allowed")
    return result
def stringNumber(x):
  return("{:,}".format(x))