# -*- coding: utf-8 -*-
"""CS5103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153zLPwLEfbFyteCfVkyrhv2yOt-q_kuY
"""

import decimal

def BigNumberComputation(a,op, b):
  if "+" in op:
    result=a+b
    decResult=decimal.Decimal(result)
    print("A+B= " + format(decResult, '.3e'))
  elif (op=="-"):
    result=b-a
    decResult=decimal.Decimal(result)
    print("A+B= " + format(decResult, '.3e'))
  else:
    print("Operand Not Allowed")

def testCase1 ():
  a=7*(10**1186)
  b=16*(10**1187)
  op="+"
  result=BigNumberComputation(a, op, b)
testCase1()

def testCase2 ():
  a=7*(10**1186)
  b=16*(10**1187)
  op="-"
  result=BigNumberComputation(a, op, b)
testCase2()

def testCase3(): #Should return "Operand Not Allowed"
  a=7*10e1123
  b=16*10e1187
  op="/"
  result=BigNumberComputation(a, op, b)
testCase3()